services:

#routers
  router1:
    image: mongo
    container_name: router1
    command: mongos --port 27017 --configdb config-srv/cfg_srv1:27017,cfg_srv2:27017,cfg_srv3:27017 --bind_ip_all
    volumes:
      - ./scripts:/scripts
    ports:
      - 27117:27017
    networks:
      - my_cluster
    restart: always
  
  router2:
    image: mongo
    container_name: router2
    command: mongos --port 27017 --configdb config-srv/cfg_srv1:27017,cfg_srv2:27017,cfg_srv3:27017 --bind_ip_all
    volumes:
      - ./scripts:/scripts
    ports:
      - 27118:27017
    networks:
      - my_cluster
    restart: always

#Config Servers
  cfg_srv1:
    image: mongo
    container_name: cfg_srv1
    command: mongod --port 27017 --configsvr --replSet config-srv
    volumes:
      - ./scripts:/scripts
    ports:
      - 27119:27017
    networks:
          - my_cluster
    restart: always

  cfg_srv2:
    image: mongo
    container_name: cfg_srv2
    command: mongod --port 27017 --configsvr --replSet config-srv
    volumes:
      - ./scripts:/scripts
    ports:
      - 27120:27017
    networks:
          - my_cluster
    restart: always

  cfg_srv3:
    image: mongo
    container_name: cfg_srv3
    command: mongod --port 27017 --configsvr --replSet config-srv
    volumes:
      - ./scripts:/scripts
    ports:
      - 27121:27017
    networks:
          - my_cluster
    restart: always

#Shards

  #Shard1
  shard1a:
    image: mongo
    container_name: shard1a
    command: mongod --port 27017 --shardsvr --replSet shard1
    volumes:
      - ./scripts:/scripts
    ports:
      - 27122:27017
    networks:
      - my_cluster
    restart: always

  shard1b:
    image: mongo
    container_name: shard1b
    command: mongod --port 27017 --shardsvr --replSet shard1
    volumes:
      - ./scripts:/scripts
    ports:
      - 27123:27017
    networks:
      - my_cluster
    restart: always

  shard1c:
    image: mongo
    container_name: shard1c
    command: mongod --port 27017 --shardsvr --replSet shard1
    volumes:
      - ./scripts:/scripts
    ports:
      - 27124:27017
    networks:
      - my_cluster
    restart: always

  #Shard2
  shard2a:
    image: mongo
    container_name: shard2a
    command: mongod --port 27017 --shardsvr --replSet shard2
    volumes:
      - ./scripts:/scripts
    ports:
      - 27125:27017
    networks:
      - my_cluster
    restart: always

  shard2b:
    image: mongo
    container_name: shard2b
    command: mongod --port 27017 --shardsvr --replSet shard2
    volumes:
      - ./scripts:/scripts
    ports:
      - 27126:27017
    networks:
      - my_cluster
    restart: always

  shard2c:
    image: mongo
    container_name: shard2c
    command: mongod --port 27017 --shardsvr --replSet shard2
    volumes:
      - ./scripts:/scripts
    ports:
      - 27127:27017
    networks:
      - my_cluster
    restart: always

  #Shard3
  shard3a:
    image: mongo
    container_name: shard3a
    command: mongod --port 27017 --shardsvr --replSet shard3
    volumes:
      - ./scripts:/scripts
    ports:
      - 27128:27017
    networks:
      - my_cluster
    restart: always

  shard3b:
    image: mongo
    container_name: shard3b
    command: mongod --port 27017 --shardsvr --replSet shard3
    volumes:
      - ./scripts:/scripts
    ports:
      - 27129:27017
    networks:
      - my_cluster
    restart: always

  shard3c:
    image: mongo
    container_name: shard3c
    command: mongod --port 27017 --shardsvr --replSet shard3
    volumes:
      - ./scripts:/scripts
    ports:
      - 27130:27017
    networks:
      - my_cluster
    restart: always

networks:
  my_cluster:
    driver: bridge